### ISSUE TITLE
文档讨论

### ISSUE THREAD

**Issue by ylc395** [UESTC-FEDOG/Ace-agents-Preparations-1#1]
Map类内部建议使用一个类GridPoint，用来表示每一格。具有以下属性/方法：
- 构造器：接收数字x,数字y和一个构造函数（Wall、Agent等），为实例添加以下属性
- coordinate：数组，表示该格的坐标
- placeholder：可能是Wall实例、File实例、Agent实例或null，表示该格上是什么东西

Map类这么修改：
- map：一个数组，成员是GridPoint实例
- init：生成一个新地图（即修改该实例的map属性）
- 构造器：在构造函数内即调用init方法

Wall类（实例表示一块墙而不是全部墙）可以添加静态方法`Wall.generateWalls`，返回一个表示全部墙的矩阵。Map.prototype.init可以调用这个静态方法

**Comment by ylc395** [comment]
还有其实可以在.js文件里（只写函数名不写函数体），按照jsdoc的格式写注释，就可以用工具生成文档了

**Comment by kkmikako** [comment]
应该像是jsdunk？不知道可以这么生成，还是思维太局限了
